### ISSUE TITLE
PyPI hosting

### ISSUE THREAD

**Issue by TomasTomecek** [andialbrecht/build_manpage#4]
Would be awesome if this was hosted on PyPI so other people can use it easily. I miss a functionality like this in python so much.

**Comment by andialbrecht** [comment]
Maybe it would be easier to just copy the module to your sources. I don't plan to update this script anymore. It's just here for reference :)

**Comment by TomasTomecek** [comment]
> Maybe it would be easier to just copy the module to your sources. 

I'm sorry but no.

1. licensing
2. maintenance

**Comment by andialbrecht** [comment]
You're absolutely right! At least the licensing issue is a good point.

Maintenance is a more general problem since I've published this code about
two years ago because it was floating around the internet for a while but
without any proper licensing terms. But I don't want to maintain this piece
of code anymore. It's verrry old and not tested at all. That's the main
reason I don't want to upload it to PyPI.

Maybe you're interested in taking over "project" ownership? ;)


Tomas Tomecek <notifications@github.com> schrieb am Fr., 24. Nov. 2017 um
10:03 Uhr:

**Comment by TomasTomecek** [comment]
> But I don't want to maintain this piece of code anymore.

I completely understand. I didn't meant to ask you to do it, I just wanted to know whether you would be interested.

For the record, I'm also not interested in the maintenance role.

**Comment by andialbrecht** [comment]
Tomas Tomecek <notifications@github.com> schrieb am Fr., 24. Nov. 2017 um
12:19 Uhr:

> But I don't want to maintain this piece of code anymore.
>
> I completely understand. I didn't meant to ask you to do it, I just wanted
> to know whether you would be interested.
>
> For the record, I'm also not interested in the maintenance role.
>
Let me know if I can do anything else that would make it easier to
integrate this script for your project.
